Address a fatal error when using 'AMP For WordPress' plugin.
Fatal error: Uncaught Error: Call to a member function canonical() on null in
plugins/yoastseo-amp/classes/frontend.php on line 173

With the 'amp' plugin's new version 0.7,
the filter 'amp_post_template_data' now runs after
'amp_post_template_metadata'
But the method YoastSEO_AMP_Frontend::fix_amp_post_data()
relied on 'amp_post_template_data' to run earlier,
in order to run:
$this->front = WPSEO_Frontend::get_instance();
So this instantiates that class in fix_amp_post_data(),
if it wasn't already.
@link http://wordpress.org/plugins/amp